- hosts: all
  become: yes
  vars:
    mysql_root_pass: wordpress

  tasks:

  - name: Add repositories
    apt_repository: repo={{ item }}
    with_items:
      - "ppa:brightbox/ruby-ng"
      - "ppa:ondrej/php"

  - name: Install common packages
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - git
      - build-essential
      - ruby-dev
      - libsqlite3-dev
      - jq
      - subversion
      - curl
      - gettext
      - python-mysqldb
      - imagemagick
      - net-tools
      - ruby2.7
      - ruby2.7-dev
      - software-properties-common
      - python3-software-properties

  # Apache2
  - name: Ensure apache is installed
    apt: pkg=apache2 state=latest
  - name: Activate mod rewrite
    apache2_module: state=present name=rewrite
  - name: Activate mod ssl
    apache2_module: state=present name=ssl
  - name: Make sure apache is running
    action: service name=apache2 state=started enabled=true

  # MySQL
  - name: Set MySQL root password before installing
    debconf:
      name: mysql-server
      question: mysql-server/root_password
      value: "{{mysql_root_pass | quote}}"
      vtype: password
  - name: Confirm MySQL root password before installing
    debconf:
      name: mysql-server
      question: mysql-server/root_password_again
      value: "{{mysql_root_pass | quote}}"
      vtype: password
  - name: Install MySQL
    apt: pkg=mysql-server state=latest update_cache=yes
  - name: Make sure MySQL is running
    action: service name=mysql state=started enabled=true

  # PHP
  - name: Install PHP packages
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - php7.4
      - libapache2-mod-php7.4
      - php7.4-cli
      - php7.4-dev
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-gd
      - php7.4-curl
      - php7.4-zip
      - php7.4-xml
      - php-xdebug
      - php-imagick
    notify: restart-apache

  # Node.js
  - name: Install Node.js PPM
    shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - name: Install Node.js
    apt: name=nodejs state=latest

  handlers:
    - name: restart-apache
      action: service name=apache2 state=restarted
    - name: restart-mysql
      action: service name=mysql state=restarted
